spring.application.name=atdd-gamificacao

# Para usar o PostgreSQL via Docker (Perfil padrão)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Para acessar o Swagger: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html